Bugfix/ocbm 149 regression testing mastery
OCBM/OCBM-FE pull request #21
Opened 2023-11-13 11:25 UTC by Roslind-Vasantha

Pull Request Title

OCBM 149 - Regression Testing - Mastery bugfix

Description:
Completely refactored mastery. Fixed the issues and alignment issues. 

Checklist

 Task Done 1: Corrected an icon name in the icons folder and delete user module
 Task Done 2: Added label and label classname in th file uploader component and updated its type
 Task Done 3: Removed console log in the table component
 Task Done 4: Improved mastery element UI
 Task Done 5: Completely refactored mastery machine - fixed the type and alignment issues, separated the edit,delete and success modals, added types, improved logic.
 Task Done 6: Improved mastery machine line removing type errors and UI issues and warnings. 
 Task Done 7: Improved mastery plant by removing type errors and UI issues and warnings. 
 Task Done 8: Completely refactored mastery shop - fixed the type and alignment issues, separated the edit,delete and success modals, added types, improved logic.
 Task Done 8: Removed the misspellings in the sitemap and machine line services.

2023-11-13 13:15 UTC, chandran-kannan approved these changes

2023-11-13 13:22 UTC, chandran-kannan requested changes

2023-11-13 13:22 UTC, chandran-kannan commented on src/components/reusable/fileuploader/index.tsx
>    const handleStatusIcon = (status: FileUploadStatusType) => {
nice 👍🏽

2023-11-14 09:14 UTC, Roslind-Vasantha commented on src/utils/sitemap.ts
> +    add: '/machineLine',
fixed it

2023-11-14 10:48 UTC, chandran-kannan approved these changes

2023-11-14 10:48 UTC, merged