Feature/ocbm 157 mastery element api integration
OCBM/OCBM-FE pull request #45
Opened 2023-11-28 16:28 UTC by Roslind-Vasantha

Title : Mastery - Element (Element Services and API Integration)

Description: Mastery Element tab with complete UI and functionality

Task done: 
 1. added element paths in the sitemap.
 2. created element services (get, add, edit and delete).
 3. integrated api (get, add, edit and delete) in the Element tab.

Screenshots: 
![image](https://github.com/OCBM/OCBM-FE/assets/131864208/8d98b52f-c92b-498a-8403-30a32c8b0b76)
![image](https://github.com/OCBM/OCBM-FE/assets/131864208/8808ccd4-6240-4f15-b724-c1318708b0bb)
![image](https://github.com/OCBM/OCBM-FE/assets/131864208/7757827f-7394-48ab-9b92-188799beb24a)
![image](https://github.com/OCBM/OCBM-FE/assets/131864208/11201fe3-579e-42c9-ab5d-be88207879af)
![image](https://github.com/OCBM/OCBM-FE/assets/131864208/d9e11337-e50d-41bb-b842-a1732a5d6b14)
![image](https://github.com/OCBM/OCBM-FE/assets/131864208/9d30fba4-1c67-46dd-94b7-36853bb6a1bd)
![image](https://github.com/OCBM/OCBM-FE/assets/131864208/97db0f2c-259a-4375-93d9-944e0729ef30)
![image](https://github.com/OCBM/OCBM-FE/assets/131864208/454e1639-5263-474d-b0c4-e5154a78765b)

Reviewers: @chandran-kannan

2023-12-01 08:59 UTC, chandran-kannan requested changes

2023-12-01 08:59 UTC, chandran-kannan commented on src/services/elementServices.ts
> +    } catch (error) {
add error toast

2023-12-01 11:40 UTC, Roslind-Vasantha commented on src/services/elementServices.ts
> +    } catch (error) {
Added it. @chandran-kannan

2023-12-07 05:55 UTC, chandran-kannan approved these changes

2023-12-07 05:56 UTC, merged